config/routes.rb
Rails.application.routes.draw do
	root 'forms#index'
  resources :forms
  devise_for :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/checklist.rb
class Checklist < ApplicationRecord
	has_many :questions,  inverse_of: :checklist, dependent: :destroy
	belongs_to :user
	validates_presence_of :questions
	validates_associated :questions
	validates :title, presence: true, length: { minimum: 5, maximum: 140}
	validates :description, presence: true, length: { minimum: 5, maximum: 300}
	accepts_nested_attributes_for :questions, reject_if: proc { |attributes| attributes[:question_text].blank? }, allow_destroy: true
end

app/models/form.rb
class Form < ApplicationRecord
	has_many :questions,  inverse_of: :form, dependent: :destroy
  belongs_to :user
	validates_presence_of :questions
	validates_associated :questions
	validates :title, presence: true, length: { minimum: 5, maximum: 140}
	validates :description, presence: true, length: { minimum: 5, maximum: 300}
	accepts_nested_attributes_for :questions, reject_if: proc { |attributes| attributes[:question_text].blank? }, allow_destroy: true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :form, inverse_of: :questions
  validates :question_text, presence: true, length: { minimum: 5, maximum: 140}
	validates :question_description, presence: true, length: { minimum: 5, maximum: 300}
end

app/models/user.rb
class User < ApplicationRecord
	has_many :forms
  has_many :checklists
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/checklists_controller.rb
class ChecklistsController < ApplicationController
end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
  def index
    @forms = Form.all
  end

  def show
    set_form
  end

  def new
    @form = current_user.forms.new
    @form.questions.build
  end

  def edit
    set_form
  end

  def create
    @form = current_user.forms.build(form_params.merge(status: 'Draft'))
    if @form.save
      redirect_to @form
    else
      render 'new'
    end
  end

  def update
    set_form
    # assign_attributes assign new attributes but in database old
    @form.assign_attributes(form_params)
    @form.published_at = DateTime.now if @form.status == 'Published'
    if @form.save
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def destroy
    set_form
    @form.destroy
    redirect_to root_path
  end

  private

    def set_form
      @form = current_user.forms.find(params[:id])
    end

    def form_params
      params.require(:form).permit(:title, :description, :status, :user_id, questions_attributes: [:id, :question_text, :question_description, :_destroy])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checklists_helper.rb
module ChecklistsHelper
end

app/helpers/forms_helper.rb
module FormsHelper
end

app/views/checklists/_form.html.erb
<div class="center">
  <%= form_with(scope: @checklist, url: url, method: method, local: true) do |f| %>

    <%= render 'shared/error_explanation' %>

    <div class="row">
      <div class="input-field col s6">
        <%= f.text_field :title, placeholder: 'Checklist title' %>
      </div>
      <div class="input-field col s6">
        <%= f.submit "Save", class: "waves-effect cyan lighten-1 btn" %>
      </div>
      <div class="input-field col s8">
        <%= f.text_field :description, placeholder: 'Checklist description' %>
      </div>
    </div>
    <div class="question_block">
      <%= f.fields_for :questions do |question_form| %>
        <%= question_form.text_field :question_text, placeholder: 'Question text' %><br>
        <%= question_form.text_field :question_description, placeholder: 'Question detailed description' %>
      <% end %>
    </div>
  <% end %>
  <a class="btn-floating btn-large cyan lighten-1"><i class="material-icons">+</i></a>
</div>

app/views/checklists/index.html.erb
<% if user_signed_in? %>
  <button class="btn-large grey lighten-3"><%= link_to "Add checklist", new_checklist_path %></button>
  <table class="highlight">
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Status</th>
        <th>Published</th>
        <th colspan="3">Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @checklists.each do |checklist| %>
        <tr>
          <td><%= checklist.title %></td>
          <td><%= checklist.description %></td>
          <td><%= checklist.status %></td>
          <td><%= checklist.published_at %></td>
          <td>
            <%= link_to edit_checklist_path(checklist) do %>
              <i class="material-icons ">create</i> 
            <% end %>
          </td>
          <td>
              <%= link_to checklist_path(checklist, checklist: {status: 'Published'}), method: :put do %>
                <i class="material-icons">remove_red_eye</i> Published
              <% end %>
          </td>
          <td>
            <%= link_to checklist, method: :delete, data: { confirm: 'Are you sure?' } do %>
              <i class="material-icons">delete</i> Remove
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
 <h3 class="center"><button class= "waves-effect cyan lighten-5 btn"><%= link_to "Log in", user_session_path %></button> to start create checklist<br>
  <button class= "waves-effect orange lighten-4 btn"><%= link_to "Sign up", new_user_registration_path %></button> if you don't have an account</h3>
<% end %>

app/views/forms/_form.html.erb
<div class="center">
  <%= form_with(scope: @form, url: url, method: method, local: true) do |f| %>

    <%= render 'shared/error_explanation' %>

    <div class="row">
      <div class="input-field col s6">
        <%= f.text_field :title, placeholder: 'Checklist title' %>
      </div>
      <div class="input-field col s6">
        <%= f.submit "Save", class: "waves-effect cyan lighten-1 btn" %>
      </div>
      <div class="input-field col s8">
        <%= f.text_field :description, placeholder: 'Checklist description' %>
      </div>
    </div>
    <div class="question_block">
      <%= f.fields_for :questions do |question_form| %>
        <%= question_form.text_field :question_text, placeholder: 'Question text' %><br>
        <%= question_form.text_field :question_description, placeholder: 'Question detailed description' %>
      <% end %>
    </div>
  <% end %>
  <a class="btn-floating btn-large cyan lighten-1"><i class="material-icons">+</i></a>
</div>

app/views/forms/edit.html.erb
<%= render 'form', method: 'patch', url: form_path(@form) %>

app/views/forms/index.html.erb
<% if user_signed_in? %>
  <button class="btn-large grey lighten-3"><%= link_to "Add checklist", new_form_path %></button>
  <table class="highlight">
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Status</th>
        <th>Published</th>
        <th colspan="3">Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @forms.each do |form| %>
        <tr>
          <td><%= form.title %></td>
          <td><%= form.description %></td>
          <td><%= form.status %></td>
          <td><%= form.published_at %></td>
          <td>
            <%= link_to edit_form_path(form) do %>
              <i class="material-icons">create</i> 
            <% end %>
          </td>
          <td>
              <%= link_to form_path(form, form: {status: 'Published'}), method: :put do %>
                <i class="material-icons">remove_red_eye</i> Published
              <% end %>
          </td>
          <td>
            <%= link_to form, method: :delete, data: { confirm: 'Are you sure?' } do %>
              <i class="material-icons">delete</i> Remove
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
 <h3 class="center"><button class= "waves-effect cyan lighten-5 btn"><%= link_to "Log in", user_session_path %></button> to start create checklist<br>
  <button class= "waves-effect orange lighten-4 btn"><%= link_to "Sign up", new_user_registration_path %></button> if you don't have an account</h3>
<% end %>

app/views/forms/new.html.erb
<div class="row">
  <div class="col s1">
    <%= link_to forms_path, data: { confirm: 'Unsaved changes will clear on going back. Clear?' } do %>
      <i class="medium material-icons">arrow_back</i>
    <% end %>
  </div>

  <div class="col s11">
    <%= render 'form', method: 'post', url: forms_path %>
  </div>
</div>

app/views/forms/show.html.erb
<div class="center">
	<h1><%= @form.title %></h1>
	<p><%= @form.description %></p>
	<%= link_to "Back to checklists", forms_path, class: "waves-effect cyan lighten-1 btn"%>
</div>

app/views/layouts/_header.html.erb
<header>
  <nav class="nav-extended">
    <div class="nav-wrapper">
      <div class="brand-logo"><%= link_to "Checklist system", root_path, id: "logo" %></div>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <% if user_signed_in? %>
          <ul id="nav-mobile" class="right hide-on-med-and-down">
            <ul>
              <li><%= link_to "Settings", edit_user_registration_path %></li>
              <li>
                <%= link_to "Log out", destroy_user_session_path, method: :delete %>
              </li>
            </ul>
          </ul>
        <% else %>
          <li><%= link_to "Log in", user_session_path %></li>
        <% end %>
      </ul>
    </div>
    <div class="nav-content">
      <ul class="tabs tabs-transparent">
        <li class="tab disabled"><%= link_to "Filled checklist", "#" %></li>
        <li class="tab"><%= link_to "Configure checklist", forms_path %></li>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChecklistSystem</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/js/materialize.min.js"></script>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_error_explanation.html.erb
<% if @form.errors.any? %>
	<div id="error_explanation">
	  <h2>
	    <%= pluralize(@form.errors.count, "error") %> prohibited
	    this form from being saved:
	  </h2>
	  <ul>
	    <% @form.errors.full_messages.each do |msg| %>
	      <li><%= msg %></li>
	    <% end %>
	  </ul>
	</div>
<% end %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>